# To use:
#
#     pre-commit run -a
#
# Or:
#
#     pre-commit install  # (runs every time you commit in git)
#
# To update this file:
#
#     pre-commit autoupdate
#
# See https://github.com/pre-commit/pre-commit
repos:
  # Standard hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
        args: ["--unsafe"] # Fixes errors parsing custom YAML constructors like ur_description's !degrees
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: fix-byte-order-marker

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.6
    hooks:
      - id: clang-format
        files: \.(c|cc|cxx|cpp|frag|glsl|h|hpp|hxx|ih|ispc|ipp|java|m|proto|vert)$
        # -i arg is included by default by the hook
        args: ["-fallback-style=none"]

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.27.1
    hooks:
      - id: yamllint
        args:
          [
            "--no-warnings",
            "--config-data",
            "{extends: default, rules: {line-length: disable, braces: {max-spaces-inside: 1}}}",
          ]
        types: [text]
        files: \.(yml|yaml)$

  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.12.2
    hooks:
      - id: markdown-link-check
        args:
          - "-c"
          - "markdown-link-check-config.json"

  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.10
    hooks:
      - id: cmake-format
      - id: cmake-lint
        args:
          - "--disabled-codes=C0301" # Disable Line too long lint
          - "--suppress-decorations"

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      # Use Prettier to lint XML files because, well.. its rules are prettier than most linters, as the name implies.
      # Also we use it in the UI, so it's familiar.
      - id: prettier
        additional_dependencies:
          - "prettier@3.1.0"
          - "@prettier/plugin-xml@3.3.1"
        files: \.(xml|xacro)$
